### ISSUE TITLE
Keine Verbindung zur Datenbank möglich

### ISSUE THREAD

**Issue by HerrVergesslich** [SmartCity-2022/Service-MainHub#8]
Das Backend kann keine Verbindung zur MySQL-DB herstellen:

Fehler Antwort des Servers:
```json
{"msg":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'mainhub'@'192.168.1.92' (using password: NO)","sqlState":"28000","fatal":true}}
```

Anscheinend wird kein Passwort mit gesendet...

Könnte an der Groß-/Kleinschreibung liegen beim erstellen des Connection Pools.

**Comment by Paddy369** [comment]
Fixed
